name: Project Workflow Check
run-name: ${{ github.actor }} is running Project Workflow Check
on:
  push:
    branches:
      - main

jobs:
  Explore-Project-Workflow-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Python Installation
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Necessary Python package Installation
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      - name: Create .kaggle directory
        run: mkdir -p ~/.kaggle
    
      - name: Copy kaggle.json
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}
        run: |
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          cat ~/.kaggle/kaggle.json  
    
      - name: Set permissions for kaggle.json
        run: chmod 600 ~/.kaggle/kaggle.json
    
      - name: Verify kaggle.json file presence
        run: ls -la ~/.kaggle  # Add this line to list the content of the directory (you can remove it later)
    
      - name: Running Unit Test
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh

      - run: echo "🍏 This job's status is ${{ job.status }}."
